spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/External
          jwk-set-uri: http://localhost:8080/realms/External/protocol/openid-connect/certs